apiVersion: v1
kind: Namespace
metadata:
  name: hotels
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotelsdep
  namespace: hotels
  labels:
    app: hotels
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  selector:
    matchLabels:
      app: hotels
  template:
    metadata:
      labels:
        app : hotels
        language : go
        version : v2
        type: utils
    spec:
      containers:
      - name: hoteles-container
        image: ghcr.io/go-elevate/k8s4arch-hotels:monolith-v2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 1
          successThreshold: 1

