apiVersion: batch/v1
kind: CronJob
metadata:
  name: hotels-cron
  namespace: hotels-Dev
spec:
  schedule: "* 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hotels-cron
            image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
            imagePullPolicy: Always
            command: ["python", "report.py"]
          restartPolicy: Never
