apiVersion: v1
kind: Namespace
metadata:
  name: hotels
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: hotels
data:
  DB_PATH: /db/hotels.json
  DB_TABLE: hotels
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotelsdep
  namespace: hotels
  labels:
    app: hotels
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  selector:
    matchLabels:
      app: hotels
  template:
    metadata:
      labels:
        app : hotels
        language : go
        version : v2
        type: backend
    spec:
      containers:
      - name: hoteles-container-frontend
        image: ghcr.io/go-elevate/k8s4arch-hotels-frontend:slim
        imagePullPolicy: Always
        envFrom: 
        - configMapRef:
           name: app-config
      - name: hoteles-container-backend
        image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
        imagePullPolicy: Always
        volumeMounts:
        - name: bbdd
          mountPath: /db/
        resources:
          requests:
            memory: 1024Mi
            cpu: 500m
          limits:
            memory: 2048Mi
            cpu: 1
        ports:
        - containerPort: 5000
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 1
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /status
            port: 5000
          failureThreshold: 30
          periodSeconds: 10
        envFrom:
        - configMapRef:
           name: app-config      
      initContainers:
      - name: hoteles-container-init
        image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
        volumeMounts:
        - name: bbdd
          mountPath: /db/
        imagePullPolicy: Always
        command: ["python"]
        args: ["migrations.py"]
        envFrom:
        - configMapRef:
           name: app-config
      volumes:
      - name: bbdd
        emptyDir: {}
